import WorkshopProfileBody from '@/components/WorkshopProfileBody';

export const metadata = {
  title: 'Talleres para Particulares | Vincula Tu Mente | María Villalba',
  description: 'Talleres sobre sexualidad, vínculos, relaciones y bienestar emocional para personas adultas. Enfoque inclusivo: todas las orientaciones, identidades y modelos de relación. María Villalba, psicóloga y sexóloga en Alcalá de Henares y online.',
  alternates: { canonical: 'https://vinculatumente.es/talleres/particulares' },
};

const profile = {
  eyebrow: 'Talleres para particulares',
  title: 'Formación para tu bienestar personal',
  description: 'Espacios formativos para personas adultas que quieren comprender mejor su mundo emocional, su sexualidad y sus relaciones. Talleres divulgativos, prácticos y libres de juicio, abiertos a todas las identidades, orientaciones y modelos de relación.',
  tagline: 'Aprende, comprende, avanza',
  color: '#F4E9F1',
  note: 'Sesiones presenciales en Alcalá de Henares y online en toda España.',
  accent: '#A87BA0',
  photo: '/media/tallerParticulares.jpg',
  photoPosition: 'center 80%',
  benefits: [
    'Bienestar emocional visible desde las primeras sesiones',
    'Herramientas de gestión emocional aplicables al día a día',
    'Espacios seguros para reflexionar, aprender y crecer en grupo',
    'Contenido basado en evidencia, sin tecnicismos ni charlas pasivas',
  ],
};

const workshopGroups = [
  {
    theme: 'Sexualidad, vínculos y diversidad',
    workshops: [
      {
        name: 'Vínculos sanos: superando celos e infidelidades',
        audience: 'Parejas y personas en relaciones vinculares',
        problem: 'Los celos descontrolados, la desconfianza, el miedo a la infidelidad o las dinámicas de control que generan sufrimiento dentro de la relación.',
        takeaways: [
          'Qué hay detrás de los celos y cómo gestionarlos sin destruir el vínculo',
          'Herramientas para reconstruir la confianza después de una ruptura de pacto',
          'Cómo comunicar lo que duele sin acusar ni herir',
          'Estrategias para sanar y decidir con claridad después de una infidelidad',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Sexualidad positiva y bienestar sexual',
        audience: 'Personas adultas y adolescentes',
        problem: 'La desinformación, la vergüenza o los mitos sobre la sexualidad que impiden vivirla de forma plena, sana y libre de culpa.',
        takeaways: [
          'Marco de la sexualidad positiva: placer, salud y derechos',
          'Herramientas de autoconocimiento sexual',
          'Cómo identificar y comunicar deseos y límites',
          'Recursos contrastados para seguir aprendiendo',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Sexualidad masculina: abordaje de la eyaculación precoz',
        audience: 'Personas adultas',
        problem: 'La eyaculación precoz, la ansiedad de rendimiento y el impacto emocional y relacional que genera en la persona y en la pareja.',
        takeaways: [
          'Qué es la eyaculación precoz y sus causas físicas y psicológicas',
          'Técnicas cognitivo-conductuales de control y regulación',
          'Cómo hablar de ello en pareja sin vergüenza ni culpa',
          'Cuándo y cómo buscar ayuda especializada',
        ],
        duration: '1,5 – 2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Sexualidad y pareja: comunicación e intimidad',
        audience: 'Parejas y vínculos',
        problem: 'La falta de comunicación sobre el sexo en la pareja, el distanciamiento íntimo, las diferencias en el deseo o la rutina que erosiona la vida sexual.',
        takeaways: [
          'Modelos de comunicación sexual en pareja',
          'Cómo hablar de deseo, fantasías y límites sin generar conflicto',
          'Herramientas para reconectar con la intimidad emocional y física',
          'Señales de que puede ser útil acudir a un/a especialista',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Consentimiento, límites y deseo',
        audience: 'Jóvenes y adultos',
        problem: 'La confusión sobre qué es el consentimiento real, la dificultad para poner límites o la presión social que condiciona el deseo y las decisiones sexuales.',
        takeaways: [
          'Qué es el consentimiento y cómo se expresa y reconoce en la práctica',
          'Cómo identificar y comunicar los propios límites con claridad',
          'Diferencia entre deseo, presión y obligación',
          'Estrategias para actuar si algo no se ha sentido bien',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Psicología afirmativa LGTBI+',
        audience: 'Personas adultas y adolescentes',
        problem: 'El estrés de minorías, la homofobia o transfobia interiorizada, la falta de referentes o el impacto psicológico de crecer en un entorno no afirmativo.',
        takeaways: [
          'Qué es la psicología afirmativa y por qué cambia la forma de trabajar',
          'Impacto del estrés de minorías en la salud mental',
          'Herramientas de autocuidado y resiliencia específicas para personas LGTBI+',
          'Recursos y redes de apoyo comunitario',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Apego y relaciones',
        audience: 'Adultos y parejas',
        problem: 'Los patrones relacionales repetitivos, el miedo al compromiso o al abandono, o la dificultad para crear vínculos seguros y estables a lo largo del tiempo.',
        takeaways: [
          'Qué es el apego y cómo se forma desde la infancia',
          'Los cuatro estilos de apego y cómo te afectan en tus relaciones actuales',
          'Cómo reconocer tus patrones en la relación de pareja',
          'Estrategias para construir un apego más seguro y consciente',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Amar no debería doler',
        audience: 'Jóvenes y adultos',
        problem: 'La dependencia emocional, los celos, el control o la violencia sutil en relaciones que se perciben como amor cuando en realidad generan sufrimiento.',
        takeaways: [
          'Qué diferencia el amor sano del amor que hace daño',
          'Señales de alerta en una relación: checklist práctico',
          'Por qué nos quedamos en relaciones que nos hacen daño',
          'Primeros pasos para salir o pedir ayuda',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Relaciones tóxicas y dependencia emocional',
        audience: 'Jóvenes y adultos',
        problem: 'La incapacidad de salir de relaciones dañinas, el miedo a la soledad, la fusión emocional o los patrones de dependencia que se repiten en diferentes vínculos.',
        takeaways: [
          'Qué es la dependencia emocional y cómo se diferencia del amor',
          'Perfil de la persona con dependencia y dinámicas de la relación tóxica',
          'Herramientas para construir autonomía emocional',
          'Plan de acción para salir del ciclo y no volver a él',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Grupo de relaciones tóxicas',
        audience: 'Adultos',
        problem: 'El aislamiento que genera haber vivido una relación tóxica y la necesidad de un espacio seguro con personas que han pasado por lo mismo para procesar y sanar.',
        takeaways: [
          'Espacio grupal de escucha y validación sin juicio',
          'Psicoeducación sobre relaciones tóxicas y proceso de recuperación',
          'Herramientas compartidas de regulación emocional',
          'Red de apoyo entre iguales con acompañamiento profesional',
        ],
        duration: 'Sesiones grupales regulares (1,5 h/sesión)',
        modality: 'Presencial',
      },
      {
        name: 'Grupo LGTBI+',
        audience: 'Comunidad LGTBI+',
        problem: 'La falta de espacios seguros y afirmativos donde explorar la identidad, compartir experiencias y recibir apoyo psicológico sin miedo al juicio.',
        takeaways: [
          'Espacio grupal afirmativo y confidencial',
          'Abordaje de identidad, salud mental y relacionamiento LGTBI+',
          'Herramientas de autocuidado y gestión del estrés de minorías',
          'Comunidad y red de apoyo entre iguales',
        ],
        duration: 'Sesiones grupales regulares (1,5 h/sesión)',
        modality: 'Presencial u online',
      },
    ],
  },
  {
    theme: 'Salud mental, trauma y bienestar emocional',
    workshops: [
      {
        name: 'Salud mental y regulación emocional',
        audience: 'Población general',
        problem: 'La falta de información rigurosa sobre qué es la salud mental, cómo funcionan los trastornos emocionales y las herramientas básicas de regulación que pueden marcar la diferencia en el día a día.',
        takeaways: [
          'Qué es la salud mental y por qué es un continuo, no una etiqueta',
          'Los trastornos emocionales más comunes: qué son y qué no son',
          'Herramientas básicas de regulación emocional basadas en evidencia',
          'Cuándo y cómo buscar ayuda profesional de salud mental',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Violencia de género: impacto psicológico y abordaje',
        audience: 'Población general',
        problem: 'El desconocimiento del impacto psicológico real de la violencia de género, la dificultad para identificar situaciones de violencia sutil o el miedo a cómo actuar cuando alguien cercano la está viviendo.',
        takeaways: [
          'Tipos de violencia de género: física, psicológica, económica y digital',
          'Impacto psicológico a corto y largo plazo en las víctimas',
          'Micromachismos y violencia sutil: cómo detectarlos en el entorno',
          'Cómo acompañar a alguien que está viviendo una situación de violencia',
        ],
        duration: '2 – 3 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Cómo funciona el trauma',
        audience: 'Población general',
        problem: 'La falta de comprensión sobre qué es el trauma psicológico, sus manifestaciones en el cuerpo y la conducta, y por qué algunas personas no logran "superarlo" con fuerza de voluntad.',
        takeaways: [
          'Qué es el trauma y qué lo diferencia de una experiencia difícil',
          'Cómo el trauma afecta al sistema nervioso, la memoria y la conducta',
          'Tipos de trauma: agudo, crónico y del desarrollo',
          'Por qué el trauma no se supera solo y qué herramientas funcionan',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Trauma relacional y vínculos',
        audience: 'Adultos y parejas',
        problem: 'Las dificultades en las relaciones afectivas que tienen raíz en heridas emocionales tempranas, los patrones de apego inseguro o los efectos del trauma relacional en la vida adulta y de pareja.',
        takeaways: [
          'Qué es el trauma relacional y cómo se forma en la infancia',
          'Cómo el trauma relacional afecta a los vínculos adultos y a la pareja',
          'Patrones de apego y su influencia en las relaciones íntimas',
          'Herramientas para comenzar a sanar el trauma relacional',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Ansiedad de alto funcionamiento',
        audience: 'Adultos',
        problem: 'La ansiedad que no se ve porque quien la sufre parece funcionar "muy bien por fuera", pero por dentro vive con hiperactividad mental constante, hiperexigencia y miedo al fracaso que agota sin que nadie lo detecte.',
        takeaways: [
          'Qué es la ansiedad de alto funcionamiento y por qué es tan difícil de reconocer',
          'Sus características: perfeccionismo, hipercontrol y agotamiento silencioso',
          'Estrategias de regulación y gestión cognitiva específicas para este perfil',
          'Cuándo buscar ayuda y qué tipo de intervención funciona mejor',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Duelo y pérdida',
        audience: 'Población general',
        problem: 'El duelo que no se entiende, que se minimiza o que no se permite sentir, ya sea por la muerte de alguien querido, por una ruptura, por una pérdida vital o por el fin de una etapa importante.',
        takeaways: [
          'Qué es el duelo y cuántas formas puede tomar',
          'Las fases del duelo y por qué no son lineales ni universales',
          'Diferencia entre duelo normal y duelo complicado',
          'Herramientas de autocuidado y acompañamiento durante el proceso',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
    ],
  },
  {
    theme: 'Talleres emocionales y bienestar',
    workshops: [
      {
        name: 'Inteligencia emocional aplicada al día a día',
        audience: 'Población general',
        problem: 'La dificultad para reconocer, gestionar y expresar las propias emociones en situaciones cotidianas, lo que impacta en las relaciones, las decisiones y el bienestar general.',
        takeaways: [
          'Qué es la inteligencia emocional y para qué sirve en la vida real',
          'Autoconciencia emocional: identificar lo que sientes y por qué',
          'Técnicas de gestión emocional aplicables al día a día',
          'Cómo usar la IE en relaciones, trabajo y situaciones de conflicto',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Gestión del estrés y ansiedad',
        audience: 'Adultos y jóvenes',
        problem: 'El estrés crónico, la ansiedad cotidiana o la dificultad para manejar la presión del día a día sin que afecte a la salud, las relaciones o el rendimiento.',
        takeaways: [
          'Diferencia entre estrés adaptativo y estrés que daña la salud',
          'Cómo funciona la ansiedad en el cuerpo y por qué aparece',
          'Técnicas de regulación del sistema nervioso basadas en evidencia',
          'Plan personal de gestión del estrés adaptado a tu ritmo de vida',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Mindfulness y bienestar emocional',
        audience: 'Población general',
        problem: 'La dificultad para estar presente, la mente que no para, el piloto automático que consume energía o la falta de herramientas para cultivar el bienestar emocional de forma sostenible.',
        takeaways: [
          'Qué es el mindfulness y qué dice la evidencia científica sobre sus beneficios',
          'Técnicas de atención plena aplicables al día a día',
          'Prácticas de mindfulness informal: cómo integrarlas en la rutina',
          'Herramientas de autocuidado y resiliencia emocional',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Autoestima y seguridad personal',
        audience: 'Adolescentes y adultos',
        problem: 'La baja autoestima, la inseguridad, el miedo a la opinión de los demás o la tendencia a ponerse en último lugar que limitan el desarrollo personal y el bienestar emocional.',
        takeaways: [
          'Qué es la autoestima real y qué la diferencia de la autoconfianza situacional',
          'Cómo se forma la autoestima y qué factores la deterioran',
          'Herramientas para construir una autoestima sólida y estable',
          'Estrategias de autocompasión y diálogo interno saludable',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Ansiedad silenciosa',
        audience: 'Adultos',
        problem: 'La ansiedad que no se manifiesta con ataques de pánico ni síntomas evidentes, pero que está presente en forma de preocupación constante, insomnio, tensión física o evitación que limita la vida sin que la persona la nombre como ansiedad.',
        takeaways: [
          'Qué es la ansiedad silenciosa y cómo se diferencia de la preocupación normal',
          'Señales físicas, cognitivas y conductuales que la delatan',
          'Técnicas de regulación del sistema nervioso adaptadas a este perfil',
          'Cuándo y por qué es importante buscar apoyo profesional',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Heridas emocionales y autoestima',
        audience: 'Población general',
        problem: 'Las heridas emocionales del pasado que condicionan la autoestima, la imagen de uno/a mismo/a y la forma de relacionarse, sin que se tenga conciencia de su origen ni de cómo empezar a sanarlas.',
        takeaways: [
          'Qué son las heridas emocionales y cómo se forman',
          'Relación entre heridas del pasado y autoestima en el presente',
          'Las cinco heridas nucleares: miedo, abandono, rechazo, humillación, injusticia',
          'Primeros pasos para sanar desde la autocompasión y el trabajo emocional',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Grupo de autoestima',
        audience: 'Adultos',
        problem: 'La necesidad de un espacio grupal donde trabajar la autoestima con acompañamiento profesional, el apoyo entre iguales y la validación que difícilmente se encuentra en el trabajo individual.',
        takeaways: [
          'Espacio grupal de exploración y refuerzo de la autoestima',
          'Herramientas de autoconcepto, autocompasión y seguridad personal',
          'Ejercicios vivenciales y dinámicas de crecimiento personal',
          'Red de apoyo entre iguales con acompañamiento psicológico',
        ],
        duration: 'Sesiones grupales regulares (1,5 h/sesión)',
        modality: 'Presencial u online',
      },
      {
        name: 'Grupo de ansiedad',
        audience: 'Adultos y jóvenes',
        problem: 'El aislamiento que genera la ansiedad crónica y la falta de un espacio seguro donde trabajarla con apoyo profesional y el alivio de compartirla con personas que entienden de verdad lo que significa.',
        takeaways: [
          'Espacio grupal de escucha, validación y regulación emocional',
          'Psicoeducación sobre la ansiedad y sus mecanismos',
          'Herramientas grupales de gestión y regulación del sistema nervioso',
          'Red de apoyo entre iguales con seguimiento profesional',
        ],
        duration: 'Sesiones grupales regulares (1,5 h/sesión)',
        modality: 'Presencial u online',
      },
    ],
  },
  {
    theme: 'Mujer y ciclos vitales',
    workshops: [
      {
        name: 'Maternidad y salud mental: acompañamiento en riesgo',
        audience: 'Madres, gestantes y sanitarios',
        problem: 'El sufrimiento emocional durante el embarazo, el posparto o la pérdida gestacional que no siempre se nombra como lo que es: una emergencia de salud mental que merece atención y acompañamiento especializado.',
        takeaways: [
          'Trastornos de salud mental perinatales: qué son y cómo se manifiestan',
          'Cómo detectar señales de alarma en el embarazo y el posparto',
          'Recursos de apoyo para madres, gestantes y familias',
          'Rol de los profesionales sanitarios en la detección y derivación temprana',
        ],
        duration: '2 – 3 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Acompañamiento psicológico en procesos reproductivos no normativos',
        audience: 'Profesionales y población general',
        problem: 'El impacto emocional de las pérdidas gestacionales, los tratamientos de fertilidad, los abortos o las maternidades no convencionales, que se viven con frecuencia en silencio y sin el apoyo psicológico que merecen.',
        takeaways: [
          'Qué se considera un proceso reproductivo no normativo y por qué importa nombrarlo',
          'Impacto psicológico del duelo perinatal, la infertilidad y el aborto',
          'Cómo acompañar sin minimizar: herramientas para familias y profesionales',
          'Recursos especializados y redes de apoyo disponibles',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Salud mental y ciclo menstrual',
        audience: 'Mujeres',
        problem: 'La falta de información sobre la influencia del ciclo menstrual en el estado emocional, el sueño, la energía y el bienestar psicológico, y la normalización del malestar que dificulta pedir ayuda.',
        takeaways: [
          'Cómo las hormonas del ciclo menstrual influyen en la salud mental',
          'Qué es el TDPM y cómo diferenciarlo de la "sensibilidad normal"',
          'Estrategias de autocuidado adaptadas a cada fase del ciclo',
          'Cuándo el malestar requiere atención psicológica especializada',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Menopausia y bienestar emocional',
        audience: 'Mujeres adultas',
        problem: 'Los cambios emocionales, cognitivos y relacionales que acompañan a la menopausia, que a menudo se minimizan o se tratan solo desde lo físico, dejando de lado el impacto psicológico real.',
        takeaways: [
          'Qué cambios emocionales y cognitivos son esperables en la menopausia',
          'Relación entre menopausia, ansiedad, insomnio y cambios de humor',
          'Herramientas de bienestar emocional adaptadas a esta etapa vital',
          'Cómo vivir la menopausia como una transición y no como una pérdida',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Maternidad real y culpa',
        audience: 'Madres y gestantes',
        problem: 'La brecha entre la maternidad idealizada y la vivencia real, la culpa que aparece cuando no se siente lo que "se debería sentir", y la soledad de no poder expresarlo sin miedo al juicio.',
        takeaways: [
          'Por qué la culpa materna es tan frecuente y de dónde viene',
          'La maternidad real vs. la maternidad que nos han vendido',
          'Herramientas para gestionar la culpa sin que consuma la experiencia',
          'Cómo construir una identidad materna auténtica y libre de expectativas externas',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Carga mental y agotamiento emocional',
        audience: 'Mujeres adultas',
        problem: 'La acumulación invisible de responsabilidades cognitivas, emocionales y logísticas que recae de forma desproporcionada sobre las mujeres y genera un agotamiento crónico que difícilmente se nombra o se reconoce como tal.',
        takeaways: [
          'Qué es la carga mental y cómo se distribuye de forma desigual',
          'Relación entre carga mental, agotamiento emocional y burnout del cuidado',
          'Estrategias de redistribución y de puesta de límites sin culpa',
          'Herramientas de autocuidado para mujeres en roles de cuidado múltiple',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'El síndrome de la impostora',
        audience: 'Mujeres',
        problem: 'La sensación persistente de no merecer los logros propios, el miedo a ser "descubierta" como un fraude y la autoexigencia que paraliza y consume energía sin que haya una base real en la que apoyarse.',
        takeaways: [
          'Qué es el síndrome de la impostora y por qué afecta especialmente a mujeres',
          'Sus manifestaciones: perfeccionismo, autosabotaje y minimización de los logros',
          'Cómo identificar las creencias limitantes que lo alimentan',
          'Herramientas cognitivas para recuperar la confianza y actuar desde la autenticidad',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
    ],
  },
];

export default function ParticularesTalleresPage() {
  return <WorkshopProfileBody profile={profile} workshopGroups={workshopGroups} />;
}
