import WorkshopProfileBody from '@/components/WorkshopProfileBody';

export const metadata = {
  title: 'Talleres para Empresas | Vincula Tu Mente | María Villalba',
  description: 'Formación para empresas: burnout, prevención del acoso laboral, igualdad, comunicación efectiva, liderazgo emocional y reducción del absentismo. Presencial y online.',
  alternates: { canonical: 'https://vinculatumente.es/talleres/empresas' },
};

const profile = {
  eyebrow: 'Formación para empresas y organizaciones',
  title: 'Equipos más sanos, organizaciones más fuertes',
  description: 'Programas de formación psicológica para empresas, departamentos de RRHH y equipos directivos. Intervenciones que mejoran el clima laboral, la igualdad y el bienestar de las personas.',
  tagline: 'Formación con impacto real en tu organización',
  color: '#EDE8F2',
  note: 'Formación presencial en tu sede o en Alcalá de Henares, y online.',
  accent: '#7A5580',
  photo: '/media/tallerEmpresas.jpg',
  benefits: [
    'Reducción del estrés, el burnout y el absentismo por causas emocionales',
    'Mejora del clima laboral, la comunicación y la cohesión de equipos',
    'Apoyo en el cumplimiento de planes de igualdad y protocolos de acoso',
    'Prevención de riesgos psicosociales con formación reconocida y adaptada',
  ],
};

const workshopGroups = [
  {
    theme: 'Empresas, igualdad y cultura organizacional',
    workshops: [
      {
        name: 'Implementación práctica de planes de igualdad',
        audience: 'Directivos, RRHH y mandos intermedios',
        problem: 'La obligación legal de contar con un plan de igualdad sin metodología participativa real, sin saber por dónde empezar o sin herramientas para hacer seguimiento y que no quede en papel mojado.',
        takeaways: [
          'Marco normativo vigente: qué obliga la ley y a quién',
          'Fases del diagnóstico de igualdad en la organización',
          'Metodología para diseñar medidas reales y medibles',
          'Cómo hacer seguimiento, evaluar y rendir cuentas del plan',
        ],
        duration: '3 – 4 h o programa estructurado',
        modality: 'Presencial u online',
      },
      {
        name: 'Igualdad de género y cultura organizacional',
        audience: 'Plantillas y dirección',
        problem: 'Una cultura organizacional en la que la igualdad se declara pero no se practica, con sesgos implícitos, brechas salariales o dinámicas que reproducen desigualdad sin que nadie lo nombre.',
        takeaways: [
          'Qué es la perspectiva de género y cómo opera en el entorno laboral',
          'Sesgos inconscientes y su impacto en la toma de decisiones',
          'Indicadores de desigualdad en la organización y cómo detectarlos',
          'Herramientas para transformar la cultura de empresa desde dentro',
        ],
        duration: '3 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Prevención del acoso y micromachismos en el trabajo',
        audience: 'Empresas',
        problem: 'Comportamientos que dañan el clima laboral y pasan desapercibidos, desde el acoso explícito hasta las microagresiones cotidianas que minan el bienestar y la confianza del equipo.',
        takeaways: [
          'Marco legal del acoso laboral y sexual en España',
          'Qué son los micromachismos y cómo identificarlos en el entorno profesional',
          'Protocolo de actuación ante situaciones de acoso',
          'Cómo construir un entorno laboral seguro y respetuoso para todos',
        ],
        duration: '2 – 3 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Diversidad LGTBI+ en la empresa',
        audience: 'Empresas y RRHH',
        problem: 'La invisibilización de las personas LGTBI+ en el entorno laboral, la falta de políticas inclusivas reales o el desconocimiento del equipo sobre cómo crear un ambiente verdaderamente seguro para todas las personas.',
        takeaways: [
          'Qué significa diversidad LGTBI+ en el contexto laboral',
          'Impacto del armario laboral en el bienestar y la productividad',
          'Protocolo de actuación ante situaciones de discriminación',
          'Cómo diseñar políticas de inclusión que vayan más allá del discurso',
        ],
        duration: '2 – 3 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Salud mental y bienestar laboral',
        audience: 'Empresas',
        problem: 'El aumento del malestar psicológico en el entorno de trabajo, el estigma que impide pedir ayuda y la falta de cultura organizacional que ponga la salud mental en el centro.',
        takeaways: [
          'Estado actual de la salud mental en el entorno laboral: datos y realidades',
          'Factores de riesgo psicosocial y cómo abordarlos desde RRHH',
          'Estrategias de resiliencia y mindfulness aplicadas al trabajo',
          'Cómo crear una cultura organizacional que cuide la salud mental',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Habilidades para la empleabilidad y gestión del cambio',
        audience: 'Personas en reorientación laboral',
        problem: 'La incertidumbre ante un cambio de trabajo o de sector, el miedo a no ser suficientemente empleable o la falta de herramientas para adaptarse a las demandas del mercado laboral actual.',
        takeaways: [
          'Autoconocimiento profesional: fortalezas, valores y estilo de trabajo',
          'Habilidades clave para la empleabilidad en el entorno actual',
          'Gestión emocional del cambio y la incertidumbre laboral',
          'Plan de acción personalizado para la transición profesional',
        ],
        duration: '2 – 3 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Resolución de problemas y pensamiento crítico',
        audience: 'Equipos y organizaciones',
        problem: 'La toma de decisiones reactiva, la falta de metodología para analizar problemas complejos o los equipos que repiten los mismos errores sin aprender de ellos.',
        takeaways: [
          'Herramientas de análisis y resolución estructurada de problemas',
          'Técnicas de pensamiento crítico y toma de decisiones bajo incertidumbre',
          'Cómo fomentar la creatividad y el pensamiento lateral en equipo',
          'Dinámica práctica aplicada a un caso real de la organización',
        ],
        duration: '2 – 3 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Comunicación y habilidades transversales',
        audience: 'Empresas',
        problem: 'La falta de habilidades interpersonales que permitan colaborar, influir y comunicarse de forma efectiva en entornos profesionales complejos y cambiantes.',
        takeaways: [
          'Competencias transversales más valoradas en el mercado laboral',
          'Comunicación oral y escrita en contextos profesionales',
          'Inteligencia social y habilidades de trabajo en equipo',
          'Estrategias para desarrollar una comunicación más impactante y auténtica',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Gestión emocional para líderes',
        audience: 'Directivos',
        problem: 'La dificultad de los líderes para gestionar sus propias emociones en situaciones de presión, crisis o conflicto, y el impacto que esto tiene en el equipo y en la cultura organizacional.',
        takeaways: [
          'Cómo las emociones del líder impactan en el clima del equipo',
          'Técnicas de autorregulación emocional para directivos',
          'Gestión de conversaciones difíciles con calma y eficacia',
          'Herramientas de liderazgo consciente basadas en evidencia',
        ],
        duration: '3 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Desconexión digital y burnout',
        audience: 'Empresas y empleados',
        problem: 'La hiperconectividad laboral, la dificultad para desconectar fuera del horario de trabajo y el agotamiento que genera la disponibilidad permanente en entornos digitalizados.',
        takeaways: [
          'Relación entre hiperconectividad, estrés crónico y burnout',
          'Marco legal del derecho a la desconexión digital en España',
          'Estrategias individuales y organizacionales de desconexión efectiva',
          'Cómo diseñar una política de desconexión digital en tu empresa',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Mujer, liderazgo y síndrome de la impostora',
        audience: 'Empresas y asociaciones',
        problem: 'Las barreras internas que frenan el liderazgo femenino: el síndrome de la impostora, el miedo al fracaso, la autoexigencia excesiva y los sesgos de género internalizados que limitan el desarrollo profesional.',
        takeaways: [
          'Qué es el síndrome de la impostora y por qué afecta especialmente a mujeres',
          'Cómo identificar las creencias limitantes que bloquean el liderazgo',
          'Estrategias cognitivas para gestionar el miedo al fracaso y la autoexigencia',
          'Herramientas para liderar desde la autenticidad y la confianza',
        ],
        duration: '2 – 3 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Protocolo de detección de violencia de género',
        audience: 'Profesionales sociosanitarios',
        problem: 'La falta de formación específica de los profesionales de la salud y los servicios sociales para detectar situaciones de violencia de género, actuar con protocolo y derivar con seguridad sin revictimizar.',
        takeaways: [
          'Marco legal y protocolo de actuación ante casos de violencia de género',
          'Cómo detectar indicadores de VG en la consulta o la atención directa',
          'Cómo preguntar y acompañar sin revictimizar ni generar más riesgo',
          'Circuito de derivación y recursos especializados disponibles',
        ],
        duration: '3 – 4 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Comunicación efectiva y negociación',
        audience: 'Equipos profesionales',
        problem: 'Los conflictos no resueltos, la comunicación deficiente entre equipos, la dificultad para negociar sin tensión o la falta de habilidades para dar y recibir feedback de forma constructiva.',
        takeaways: [
          'Modelo de comunicación asertiva aplicado al entorno profesional',
          'Técnicas de negociación basadas en intereses, no en posiciones',
          'Cómo gestionar conversaciones difíciles con clientes, colegas o superiores',
          'Herramientas de escucha activa y feedback efectivo en equipos',
        ],
        duration: '2 – 3 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Grupo de burnout y estrés',
        audience: 'Trabajadores',
        problem: 'El agotamiento crónico, la sensación de no poder más y la falta de un espacio seguro donde trabajar el burnout con acompañamiento profesional y apoyo entre iguales.',
        takeaways: [
          'Espacio grupal de escucha activa y validación sin juicio',
          'Psicoeducación sobre burnout y su proceso de recuperación',
          'Técnicas de regulación emocional y autocuidado adaptadas al entorno laboral',
          'Red de apoyo entre iguales con seguimiento profesional',
        ],
        duration: 'Sesiones grupales regulares (1,5 h/sesión)',
        modality: 'Presencial u online',
      },
    ],
  },
  {
    theme: 'Talleres corporativos',
    workshops: [
      {
        name: 'Liderazgo emocionalmente inteligente',
        audience: 'Directivos y mandos',
        problem: 'Un liderazgo que genera desgaste en el equipo, la dificultad para motivar personas en contextos de incertidumbre o la falta de habilidades emocionales para tomar decisiones bajo presión.',
        takeaways: [
          'Modelo de inteligencia emocional aplicado al liderazgo',
          'Autoconciencia y autorregulación como bases del liderazgo efectivo',
          'Cómo generar confianza y motivación en equipos diversos',
          'Gestión del propio estrés directivo sin trasladarlo al equipo',
        ],
        duration: '3 – 4 h o programa estructurado',
        modality: 'Presencial u online',
      },
      {
        name: 'Comunicación efectiva y resolución de conflictos',
        audience: 'Equipos de trabajo',
        problem: 'Los conflictos interpersonales no resueltos, la dificultad para comunicar discrepancias sin escalada o la falta de herramientas para mediar en situaciones de tensión entre personas del equipo.',
        takeaways: [
          'Modelo de comunicación efectiva en entornos laborales',
          'Técnicas de resolución de conflictos sin perder la relación profesional',
          'Cómo mediar en disputas entre personas del equipo',
          'Estrategias de comunicación asertiva para situaciones difíciles',
        ],
        duration: '2 – 3 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Trabajo en equipo y cohesión grupal',
        audience: 'Empresas',
        problem: 'Equipos que trabajan de forma aislada, la falta de coordinación entre áreas, el bajo sentido de pertenencia o la ausencia de una cultura de colaboración que impulse el rendimiento colectivo.',
        takeaways: [
          'Claves de la dinámica de grupo y los factores que hacen funcionar a un equipo',
          'Inteligencia emocional colectiva y cómo desarrollarla',
          'Herramientas de cohesión y confianza para equipos presenciales y remotos',
          'Plan de acción para mejorar la colaboración y el clima del equipo',
        ],
        duration: '3 – 4 h o programa estructurado',
        modality: 'Presencial u online',
      },
      {
        name: 'Prevención del burnout y gestión del estrés',
        audience: 'Empresas y empleados',
        problem: 'El estrés crónico que no se detecta a tiempo, el agotamiento sostenido que deriva en burnout o la pérdida de productividad por no contar con herramientas de prevención en el entorno laboral.',
        takeaways: [
          'Diferencia entre estrés, fatiga laboral y burnout: cómo detectar cada fase',
          'Factores organizacionales que generan burnout y cómo modificarlos',
          'Técnicas individuales de gestión del estrés aplicables en el día a día',
          'Plan de prevención colectiva adaptado a la realidad de la empresa',
        ],
        duration: '2 – 3 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Equipos psicológicamente seguros',
        audience: 'Empresas',
        problem: 'Equipos en los que las personas no se atreven a expresar dudas, errores o ideas por miedo al juicio, lo que bloquea la innovación, genera burnout silencioso y deteriora la confianza.',
        takeaways: [
          'Qué es la seguridad psicológica y por qué predice el rendimiento del equipo',
          'Señales de que tu equipo no se siente seguro y cómo revertirlo',
          'Prácticas de liderazgo que favorecen la confianza y la apertura',
          'Plan de acción para crear un equipo psicológicamente seguro',
        ],
        duration: '2 – 3 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Inteligencia emocional aplicada al trabajo',
        audience: 'Empresas',
        problem: 'La falta de recursos para gestionar el impacto emocional del trabajo, las relaciones laborales desgastantes o la incapacidad de reconocer y regular las propias emociones en el entorno profesional.',
        takeaways: [
          'Los cinco componentes de la inteligencia emocional y su aplicación laboral',
          'Autoconciencia emocional: cómo identificar lo que sientes en el trabajo',
          'Regulación emocional en situaciones de tensión o conflicto',
          'Cómo usar la IE para mejorar relaciones y bienestar en el equipo',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Mindfulness y work-life balance',
        audience: 'Empresas',
        problem: 'El agotamiento crónico, la incapacidad de desconectar del trabajo y la dificultad para gestionar la carga emocional y cognitiva en puestos con alta demanda.',
        takeaways: [
          'Fundamentos del mindfulness aplicados al contexto laboral',
          'Técnicas de regulación emocional y reducción del estrés',
          'Estrategias prácticas para mejorar el equilibrio vida-trabajo',
          'Rutinas de autocuidado sostenibles aplicables desde el primer día',
        ],
        duration: '2 h',
        modality: 'Presencial u online',
      },
      {
        name: 'Comunicación no violenta en empresas',
        audience: 'Equipos profesionales',
        problem: 'Los conflictos interpersonales frecuentes, la comunicación agresiva o pasivo-agresiva en el equipo, y la falta de herramientas para expresar necesidades y escuchar sin generar más tensión.',
        takeaways: [
          'Los cuatro componentes de la comunicación no violenta (CNV)',
          'Cómo aplicar la CNV en reuniones, evaluaciones y conflictos',
          'Herramientas de escucha empática en el entorno profesional',
          'Práctica con situaciones reales mediante role playing',
        ],
        duration: '2 – 3 h',
        modality: 'Presencial u online',
      },
    ],
  },
];

export default function EmpresasTalleresPage() {
  return <WorkshopProfileBody profile={profile} workshopGroups={workshopGroups} />;
}
